spring:
    application:
        name: ribbon-client

server:
    port: 7777

eureka:
    client:
        service-url:
            defaultZone: http://localhost:9999/eureka
feign:
    hystrix:
        enabled: true
