spring:
    application:
        name: sleuth-order
    sleuth:
        web:
            client:
                enabled: true
        sampler:
            # 抽样比例，默认是0.1，即10%
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411

eureka:
    client:
        service-url:
            defaultZone: http://localhost:9999/eureka/

server:
    port: 8003
