spring:
    application:
        name: admin-client

eureka:
    client:
        registryFetchIntervalSeconds: 5
        service-url:
            defaultZone: http://localhost:9999/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
        metadata-map:
            startup: ${random.int}    #needed to trigger info and endpoint update after restart

server:
    port: 8768

management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: ALWAYS
