spring:
    application:
        name: config-server
    profiles:
        active: git

eureka:
    client:
        service-url:
            defaultZone: http://localhost:9999/eureka/

server:
    port: 8888
