spring:
    cloud:
        config:
            server:
                git:
                    uri: /Users/maxpeng/Documents/Projects/microservice-training/config-repo
                    default-label: master
